/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations, useFBX } from "@react-three/drei";

export default function AvatarAndAnimation(props) {
  const group = useRef();

  const { nodes, materials, animations } = useGLTF(
    "models/avataryanimacion.glb"
  );

  const { actions } = useAnimations(animations, group);

  console.log(actions.typing);
  useEffect(() => {
    if (actions.typing) {
      actions.typing.reset().play();
      console.log(actions?.typing?.isRunning());
    }
  }, [actions?.typing]);

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />

      <mesh
        name="EyeLeft"
        castShadow
        receiveShadow
        geometry={nodes.EyeLeft.geometry}
        material={materials.Wolf3D_Eye}
        morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
      />
      <mesh
        name="EyeRight"
        castShadow
        receiveShadow
        geometry={nodes.EyeRight.geometry}
        material={materials.Wolf3D_Eye}
        morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
      />
      <mesh
        name="Wolf3D_Body"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Body.geometry}
        material={materials.Wolf3D_Body}
      />
      <mesh
        name="Wolf3D_Glasses"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Glasses.geometry}
        material={materials.Wolf3D_Glasses}
      />
      <mesh
        name="Wolf3D_Hair"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Hair.geometry}
        material={materials.Wolf3D_Hair}
      />
      <mesh
        name="Wolf3D_Head"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Head.geometry}
        material={materials.Wolf3D_Skin}
        morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
      />
      <mesh
        name="Wolf3D_Outfit_Bottom"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
        material={materials.Wolf3D_Outfit_Bottom}
      />
      <mesh
        name="Wolf3D_Outfit_Footwear"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
        material={materials.Wolf3D_Outfit_Footwear}
      />
      <mesh
        name="Wolf3D_Outfit_Top"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Outfit_Top.geometry}
        material={materials.Wolf3D_Outfit_Top}
      />
      <mesh
        name="Wolf3D_Teeth"
        castShadow
        receiveShadow
        geometry={nodes.Wolf3D_Teeth.geometry}
        material={materials.Wolf3D_Teeth}
        morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
        morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
      />
    </group>
  );
}

useGLTF.preload("models/avataryanimacion.glb");
