/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("models/computer.glb");

  return (
    <group {...props} dispose={null}>
      <group
        position={[0.142, 2.125, 1.569]}
        rotation={[0, 0.262, -0.079]}
        scale={[0.233, 0.281, 0.197]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <group
        position={[0.142, 2.125, -1.784]}
        rotation={[0, -0.262, -0.079]}
        scale={[0.233, 0.281, 0.197]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials["Material.003"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={materials["Material.003"]}
        position={[-0.097, 2.025, 0.496]}
        rotation={[0, 0.052, 0]}
        scale={[0.437, 0.804, 0.804]}
      />

      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials["Material.004"]}
        position={[0.434, 1.45, -0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials["Material.003"]}
        position={[-0.091, 2.025, -0.743]}
        rotation={[0, -0.052, 0]}
        scale={[0.437, 0.804, 0.804]}
      />
      <group position={[0.501, 0.472, 1.7]} scale={1.168}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_1.geometry}
          material={materials["Material.005"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_2.geometry}
          material={materials["glass.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_3.geometry}
          material={materials["Material.010"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007_4.geometry}
          material={materials["Material.014"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("models/computer.glb");
